-- Run after relay_company_exchange; every fixture is rolled back.
begin;
do $test$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); member uuid:=gen_random_uuid(); oa uuid:=gen_random_uuid(); ob uuid:=gen_random_uuid(); sa uuid; sb uuid; relationship uuid; request uuid; next_request uuid; expired_link jsonb; doc uuid:=gen_random_uuid(); foreign_doc uuid:=gen_random_uuid(); link jsonb; v jsonb; denied boolean;
begin
 insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values(a,'exchange-a@example.invalid','{}','{}'),(b,'exchange-b@example.invalid','{}','{}'),(outsider,'exchange-outsider@example.invalid','{}','{}'),(member,'exchange-member@example.invalid','{}','{}');
 insert into public.organizations(id,owner_id,legal_name) values(oa,a,'Requesting company'),(ob,b,'Sending company');
 insert into public.organization_members(organization_id,user_id,role) values(ob,member,'member');
 perform set_config('request.jwt.claim.sub',b::text,true);execute 'set local role authenticated';
 perform public.relay_workspace_api('settings',jsonb_build_object('organization_id',ob,'name','Sending company','listed',true));
 sb:=public.add_supplier_connection(ob,'Document source','Austria','AT','','');
 insert into public.documents(id,organization_id,supplier_id,name,kind,mime_type,storage_path,uploaded_by) values(doc,ob,sb,'Company proof.pdf','certificate','application/pdf',ob||'/'||sb||'/'||doc||'/Proof.pdf',b);
 execute 'reset role';perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 sa:=(public.relay_workspace_api('connect_company',jsonb_build_object('organization_id',oa,'company_id',ob))->>'supplier_id')::uuid;
 select id into relationship from public.supplier_relationships where supplier_id=sa;
 request:=public.prepare_information_request(relationship,'Provide company certificate',current_date+10);
 v:=public.relay_exchange_api('list',jsonb_build_object('organization_id',oa));
 if (v->>'total')::int<>1 then raise exception 'Sent request missing';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',outsider::text,true);execute 'set local role authenticated';
 denied:=false;begin perform public.relay_exchange_api('list',jsonb_build_object('organization_id',ob));exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Outsider can open inbox';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',member::text,true);execute 'set local role authenticated';
 v:=public.relay_exchange_api('list',jsonb_build_object('organization_id',ob));
 if (v->>'total')::int<>1 then raise exception 'Member cannot see inbox';end if;
 denied:=false;begin perform public.relay_exchange_api('respond',jsonb_build_object('organization_id',ob,'request_id',request,'document_ids',jsonb_build_array(doc)));exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Member can authorize document sharing';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',b::text,true);execute 'set local role authenticated';
 denied:=false;begin perform public.relay_exchange_api('respond',jsonb_build_object('organization_id',ob,'request_id',request,'document_ids',jsonb_build_array(foreign_doc)));exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Foreign document accepted';end if;
 perform public.relay_exchange_api('respond',jsonb_build_object('organization_id',ob,'request_id',request,'document_ids',jsonb_build_array(doc)));
 perform public.relay_exchange_api('respond',jsonb_build_object('organization_id',ob,'request_id',request,'document_ids',jsonb_build_array(doc)));
 execute 'reset role';perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 if not exists(select 1 from public.documents where id=doc) then raise exception 'Selected document not readable by receiver';end if;
 if exists(select 1 from public.suppliers where id=sb) then raise exception 'Private sender supplier exposed';end if;
 if (select status from public.data_requests where id=request)<>'received' then raise exception 'Request not marked received';end if;
 link:=public.relay_workspace_api('upload_link',jsonb_build_object('organization_id',oa,'supplier_id',sa,'title','Send your company files'));
 execute 'reset role';perform set_config('request.jwt.claim.sub',b::text,true);execute 'set local role authenticated';
 perform public.relay_exchange_api('share_link',jsonb_build_object('organization_id',ob,'token',link->>'token','document_ids',jsonb_build_array(doc)));
 perform public.relay_exchange_api('share_link',jsonb_build_object('organization_id',ob,'token',link->>'token','document_ids',jsonb_build_array(doc)));
 execute 'reset role';
 if (select uploads_used from public.upload_links where id=(link->>'id')::uuid)<>1 then raise exception 'Link retry double-counted';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 next_request:=public.prepare_information_request(relationship,'Another certificate request',current_date+12);
 v:=public.relay_exchange_api('list',jsonb_build_object('organization_id',oa,'direction','received'));
 if (v->>'total')::int<>0 or jsonb_array_length(v->'items')<>0 then raise exception 'Direction filter applied after pagination';end if;
 v:=public.relay_exchange_api('list',jsonb_build_object('organization_id',oa,'supplier_id',sb));
 if (v->>'total')::int<>0 or jsonb_array_length(v->'items')<>0 then raise exception 'Supplier filter applied after pagination';end if;
 expired_link:=public.relay_workspace_api('upload_link',jsonb_build_object('organization_id',oa,'supplier_id',sa,'title','Expired fixture'));
 execute 'reset role';
 update public.upload_links set expires_at=now()-interval '1 hour' where id=(expired_link->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',b::text,true);execute 'set local role authenticated';
 denied:=false;begin perform public.relay_exchange_api('share_link',jsonb_build_object('organization_id',ob,'token',expired_link->>'token','document_ids',jsonb_build_array(doc)));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Expired link accepted';end if;
 execute 'reset role';
 update public.document_shares set revoked_at=now() where document_id=doc and recipient_organization_id=oa;
 perform set_config('request.jwt.claim.sub',b::text,true);execute 'set local role authenticated';
 denied:=false;begin perform public.relay_exchange_api('respond',jsonb_build_object('organization_id',ob,'request_id',next_request,'document_ids',jsonb_build_array(doc)));exception when raise_exception then denied:=true;end;if not denied then raise exception 'Revoked share silently reactivated';end if;
 execute 'reset role';
 if not exists(select 1 from public.document_shares where document_id=doc and recipient_organization_id=oa and revoked_at is not null) then raise exception 'Revoked share no longer revoked';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 if exists(select 1 from public.documents where id=doc) then raise exception 'Receiver can still read revoked document';end if;
 execute 'reset role';

 perform set_config('request.jwt.claim.sub',a::text,true);execute 'set local role authenticated';
 perform public.relay_supplier_lifecycle('trash',jsonb_build_object('organization_id',oa,'supplier_id',sa));
 execute 'reset role';perform set_config('request.jwt.claim.sub',b::text,true);execute 'set local role authenticated';
 v:=public.relay_exchange_api('list',jsonb_build_object('organization_id',ob));if (v->>'total')::int<>0 then raise exception 'Removed request still accessible';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub','',true);execute 'set local role anon';
 denied:=false;begin perform public.relay_exchange_api('organizations');exception when insufficient_privilege then denied:=true;end;if not denied then raise exception 'Anonymous exchange allowed';end if;
 execute 'reset role';
end $test$;
rollback;
select 'Company exchange: inbox routing, tenant isolation, member permissions, explicit document ownership, idempotency, link sharing and archive revocation passed' as result;
