begin;
do $test$
declare u uuid:=gen_random_uuid(); other_user uuid:=gen_random_uuid(); org uuid:=gen_random_uuid(); sid uuid; recipient_org uuid:=gen_random_uuid(); member_user uuid:=gen_random_uuid(); doc uuid:=gen_random_uuid(); link jsonb; v jsonb; blocked boolean;
begin
 insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values(u,'trash-test@example.invalid','{}','{}'),(other_user,'trash-other@example.invalid','{}','{}');
 insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values(member_user,'trash-member@example.invalid','{}','{}');
 insert into public.organizations(id,owner_id,legal_name) values(org,u,'Trash test'),(recipient_org,other_user,'Recipient test');
 insert into public.organization_members(organization_id,user_id,role) values(org,member_user,'member');
 insert into public.company_directory(organization_id,display_name,listed) values(recipient_org,'Recipient test',true) on conflict(organization_id) do update set listed=true;
 perform set_config('request.jwt.claim.sub',u::text,true);execute 'set local role authenticated';
 perform public.add_supplier_connection(org,'Recoverable supplier','Austria','AT','','');
 select id into strict sid from public.suppliers where organization_id=org;
 insert into public.documents(id,organization_id,supplier_id,name,kind,mime_type,storage_path,uploaded_by) values(doc,org,sid,'Kept.pdf','certificate','application/pdf',org||'/'||sid||'/'||doc||'/Kept.pdf',u);
 insert into public.products(organization_id,supplier_id,name) values(org,sid,'Kept product');
 link:=public.relay_workspace_api('upload_link',jsonb_build_object('organization_id',org,'supplier_id',sid,'title','Archive test'));
 perform public.relay_workspace_api('share_documents',jsonb_build_object('organization_id',org,'recipient_id',recipient_org,'document_ids',jsonb_build_array(doc)));
 perform public.relay_supplier_lifecycle('preview',jsonb_build_object('organization_id',org,'supplier_id',sid));
 perform public.relay_supplier_lifecycle('trash',jsonb_build_object('organization_id',org,'supplier_id',sid));
 if exists(select 1 from public.suppliers where id=sid) then raise exception 'Archived row remains readable';end if;
 v:=public.relay_workspace_snapshot(jsonb_build_object('organization_id',org,'view','suppliers'));
 if (v->>'total')::int<>0 or jsonb_array_length(v->'suppliers')<>0 then raise exception 'Snapshot still includes trash';end if;
 v:=public.relay_workspace_snapshot(jsonb_build_object('organization_id',org,'view','overview'));
 if (v->'metrics'->>'suppliers')::int<>0 then raise exception 'Metrics include trash';end if;
 v:=public.relay_supplier_lifecycle('list',jsonb_build_object('organization_id',org));
 if (v->>'total')::int<>1 then raise exception 'Trash list lost supplier';end if;
 v:=public.relay_workspace_snapshot(jsonb_build_object('organization_id',org,'view','documents'));
 if jsonb_array_length(v->'documents')<>0 then raise exception 'Archived documents visible';end if;
 v:=public.relay_workspace_snapshot(jsonb_build_object('organization_id',org,'view','products'));
 if (v->>'total')::int<>0 then raise exception 'Archived products counted';end if;
 -- Direct writes are filtered by RLS; definer writes are guarded too.
 execute 'reset role';
 blocked:=false;begin update public.suppliers set city='stale write' where id=sid;exception when object_not_in_prerequisite_state then blocked:=true;end;
 if not blocked then raise exception 'Definer write bypassed archive guard';end if;
 perform set_config('request.jwt.claim.sub',member_user::text,true);execute 'set local role authenticated';
 blocked:=false;begin perform public.relay_supplier_lifecycle('restore',jsonb_build_object('organization_id',org,'supplier_id',sid));exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'Read-only member can restore supplier';end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',other_user::text,true);execute 'set local role authenticated';
 blocked:=false;begin perform public.relay_supplier_lifecycle('restore',jsonb_build_object('organization_id',org,'supplier_id',sid));exception when insufficient_privilege then blocked:=true;end;
 if not blocked then raise exception 'Cross-company restoration allowed';end if;
 if exists(select 1 from public.documents where id=doc) then raise exception 'Recipient access survived removal';end if;
 execute 'reset role';perform set_config('request.jwt.claim.sub',u::text,true);execute 'set local role authenticated';
 perform public.relay_supplier_lifecycle('restore',jsonb_build_object('organization_id',org,'supplier_id',sid));
 if not exists(select 1 from public.suppliers where id=sid) then raise exception 'Restore failed';end if;
 if not exists(select 1 from public.documents where id=doc) then raise exception 'Document lost on restore';end if;
 if exists(select 1 from public.upload_links where id=(link->>'id')::uuid and revoked_at is null) then raise exception 'Upload link reactivated';end if;
 if exists(select 1 from public.document_shares where document_id=doc and revoked_at is null) then raise exception 'Share reactivated';end if;
 v:=public.relay_workspace_snapshot(jsonb_build_object('organization_id',org,'view','suppliers'));
 if (v->>'total')::int<>1 then raise exception 'Restored snapshot incorrect';end if;
 execute 'reset role';
end $test$;
rollback;
select 'Supplier trash: RLS, snapshots, metrics, definer write guard, tenant isolation and restoration passed; fixtures rolled back' as result;
