begin;
do $test$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); member uuid:=gen_random_uuid(); oa uuid:=gen_random_uuid(); ob uuid:=gen_random_uuid(); supplier uuid; doc uuid:=gen_random_uuid(); invitation jsonb; link jsonb; reservation jsonb; share_id uuid; n integer; failed boolean;
begin
 insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data) values(a,'relay-test-owner-a@example.invalid',now(),'{}','{}'),(b,'relay-test-owner-b@example.invalid',now(),'{}','{}'),(member,'relay-test-member@example.invalid',now(),'{}','{}');
 insert into public.organizations(id,owner_id,legal_name) values(oa,a,'Relay test A'),(ob,b,'Relay test B');
 perform set_config('request.jwt.claim.sub',b::text,true); execute 'set local role authenticated';
 perform public.relay_workspace_api('settings',jsonb_build_object('organization_id',ob,'name','Relay test B','listed',true));
 execute 'reset role'; perform set_config('request.jwt.claim.sub',a::text,true); execute 'set local role authenticated';
 failed:=false; begin perform public.relay_workspace_api('settings',jsonb_build_object('organization_id',ob,'name','Intrusion')); exception when insufficient_privilege then failed:=true; end; if not failed then raise exception 'Foreign settings write allowed'; end if;
 perform public.relay_workspace_api('settings',jsonb_build_object('organization_id',oa,'name','Relay test A','listed',true));
 invitation:=public.relay_workspace_api('invite',jsonb_build_object('organization_id',oa,'email','relay-test-member@example.invalid','role','member'));
 execute 'reset role'; perform set_config('request.jwt.claim.sub',member::text,true); execute 'set local role authenticated';
 perform public.relay_workspace_api('claim_invite',jsonb_build_object('token',invitation->>'token'));
 failed:=false; begin perform public.relay_workspace_api('invite',jsonb_build_object('organization_id',oa,'email','other@example.invalid','role','admin')); exception when insufficient_privilege then failed:=true; end; if not failed then raise exception 'Member escalated permissions'; end if;
 execute 'reset role'; perform set_config('request.jwt.claim.sub',a::text,true); execute 'set local role authenticated';
 supplier:=(public.relay_workspace_api('connect_company',jsonb_build_object('organization_id',oa,'company_id',ob))->>'supplier_id')::uuid;
 if (select count(*) from public.requirements where organization_id=oa)<>3 then raise exception 'Connection did not initialize requirements'; end if;
 insert into public.documents(id,organization_id,supplier_id,name,kind,mime_type,storage_path,uploaded_by) values(doc,oa,supplier,'Proof.pdf','certificate','application/pdf',oa||'/'||supplier||'/'||doc||'/Proof.pdf',a);
 perform public.relay_workspace_api('share_documents',jsonb_build_object('organization_id',oa,'recipient_id',ob,'document_ids',jsonb_build_array(doc)));
 select id into share_id from public.document_shares where document_id=doc;
 execute 'reset role'; perform set_config('request.jwt.claim.sub',b::text,true); execute 'set local role authenticated';
 if (select count(*) from public.documents where id=doc)<>1 then raise exception 'Recipient cannot read shared document'; end if;
 if (select count(*) from public.suppliers where id=supplier)<>0 then raise exception 'Sharing exposed private supplier data'; end if;
 execute 'reset role'; perform set_config('request.jwt.claim.sub',a::text,true); execute 'set local role authenticated';
 perform public.relay_workspace_api('revoke_share',jsonb_build_object('organization_id',oa,'id',share_id));
 execute 'reset role'; perform set_config('request.jwt.claim.sub',b::text,true); execute 'set local role authenticated';
 if (select count(*) from public.documents where id=doc)<>0 then raise exception 'Revocation did not remove access'; end if;
 execute 'reset role'; perform set_config('request.jwt.claim.sub',a::text,true); execute 'set local role authenticated';
 perform public.relay_workspace_api('record_certificate',jsonb_build_object('organization_id',oa,'supplier_id',supplier,'document_id',doc,'standard','ISO 9001','valid_from','2026-01-01','valid_until','2027-01-01'));
 if (select verification_status from public.documents where id=doc)<>'verified' then raise exception 'Certificate review was not atomic'; end if;
 link:=public.relay_workspace_api('upload_link',jsonb_build_object('organization_id',oa,'supplier_id',supplier,'title','Test intake'));
 execute 'reset role'; execute 'set local role service_role';
 reservation:=public.relay_intake_api('reserve',jsonb_build_object('token',link->>'token','file_count',1));
 update public.intake_reservations set created_at=now()-interval '11 minutes' where id=(reservation->>'reservation_id')::uuid;
 if (public.relay_intake_api('info',jsonb_build_object('token',link->>'token'))->>'remaining')::integer<>5 then raise exception 'Stale upload capacity not recovered'; end if;
 reservation:=public.relay_intake_api('reserve',jsonb_build_object('token',link->>'token','file_count',1));
 doc:=gen_random_uuid();
 perform public.relay_intake_api('finish',jsonb_build_object('reservation_id',reservation->>'reservation_id','name','Test sender','email','sender@example.invalid','files',jsonb_build_array(jsonb_build_object('id',doc,'name','Guest.pdf','kind','certificate','mime_type','application/pdf','path',oa||'/'||supplier||'/'||doc||'/Guest.pdf'))));
 if (select verification_status from public.documents where id=doc)<>'unverified' then raise exception 'Guest submission falsely verified'; end if;
 if (select uploaded_by from public.documents where id=doc) is not null then raise exception 'Guest actor impersonated'; end if;
 failed:=false;begin perform public.relay_intake_api('finish',jsonb_build_object('reservation_id',reservation->>'reservation_id'));exception when others then if sqlerrm='Submission is no longer pending' then failed:=true;else raise;end if;end;
 if not failed then raise exception 'Submission replay accepted'; end if;
 execute 'reset role';
end $test$;
rollback;
select 'tenant, invitation, role, sharing revocation, certificate and guest intake replay assertions passed' as result;
