import { MotionWords } from "../components/Motion";
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowUpRight, Plus, Download, LogOut, RefreshCw } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { PublicHeader, PublicFooter } from './marketing/Website';
import { Button, Input, Dialog, EmptyState, Badge } from '../components/ui';
import { requireSupabase } from '../lib/supabase';
import type { Database } from '../lib/database.types';
import { useFeedback } from '../components/Feedback';
type Row<K extends keyof Database['public']['Tables']> = Database['public']['Tables'][K]['Row'];
function message(error: unknown) { return error instanceof Error ? error.message : typeof error === 'object' && error && 'message' in error ? String(error.message) : 'Please try again.'; }
export function CloudAccount({signup=false}:{signup?:boolean}) {
 const navigate=useNavigate();
 const [busy,setBusy]=useState(false), [error,setError]=useState(''), [email,setEmail]=useState(''), [sent,setSent]=useState(false), [retryAt,setRetryAt]=useState(0), [now,setNow]=useState(Date.now());
 const [details,setDetails]=useState({full_name:'',company_name:''});
 const destination=()=>{const token=sessionStorage.getItem('relay-pending-invite');return token?'/join#token='+token:'/cloud';};
 useEffect(()=>{const client=requireSupabase();let active=true;void client.auth.getUser().then(({data})=>{if(active&&data.user)navigate(destination(),{replace:true});});const {data:{subscription}}=client.auth.onAuthStateChange((_event,session)=>{if(session)navigate(destination(),{replace:true});});return()=>{active=false;subscription.unsubscribe();};},[navigate]);
 useEffect(()=>{if(!sent)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[sent]);
 useEffect(()=>{setSent(false);setError('');},[signup]);
 async function sendCode(address:string,profile=details){
  setBusy(true);setError('');
  try {const {error}=await requireSupabase().auth.signInWithOtp({email:address,options:{shouldCreateUser:signup,emailRedirectTo:window.location.origin+'/account',...(signup?{data:profile}:{})}});if(error)throw error;setEmail(address);setDetails(profile);setSent(true);setRetryAt(Date.now()+60000);setNow(Date.now());}
  catch(e){setError(message(e));}finally{setBusy(false);}
 }
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);
  if(!sent){await sendCode(String(form.get('email')).trim(),{full_name:String(form.get('name')||'').trim(),company_name:String(form.get('company')||'').trim()});return;}
  setBusy(true);setError('');try{const token=String(form.get('code')).replace(/\s/g,'');const {data,error}=await requireSupabase().auth.verifyOtp({email,token,type:'email'});if(error)throw error;if(!data.session)throw new Error('Please request a new code and try again.');navigate(destination(),{replace:true});}catch(e){setError(message(e));}finally{setBusy(false);}
 }
 const remaining=Math.max(0,Math.ceil((retryAt-now)/1000));
 return <div className="public-site"><PublicHeader/><main id="main" tabIndex={-1} className="public-main access-main"><section className="access-copy"><span className="eyebrow">YOUR CONNECTED WORKSPACE.</span><h1><MotionWords>{signup?'A place for':'Back to'}</MotionWords><br/><MotionWords>your network.</MotionWords></h1><p>Company information.<br/>Private documents.<br/>A clearer picture.</p><span className="access-attribution">A product of VOVERE</span></section><section className="access-panel"><h2>{sent?'Check your inbox.':signup?'Create your account.':'Sign in to Relay.'}</h2><p>{sent?`Enter the verification code sent to ${email}. You can also use the sign-in link if your email contains one.`:'A secure code, sent to your work email. No password to remember.'}</p><form onSubmit={submit} key={sent?'code':'email'}>{sent?<label>Verification code<Input autoFocus required name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9 ]{6,12}" minLength={6} maxLength={12} placeholder="Enter your code"/></label>:<>{signup&&<><label>Your name<Input required name="name" maxLength={100} autoComplete="name" defaultValue={details.full_name}/></label><label>Company name<Input required name="company" maxLength={160} autoComplete="organization" defaultValue={details.company_name}/></label></>}<label>Work email<Input required type="email" name="email" autoComplete="email" maxLength={254} defaultValue={email}/></label></>}{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit" disabled={busy}>{busy?'Please wait…':sent?'Verify and continue':'Send me a code'}<ArrowUpRight size={16}/></Button></form>{sent?<><button className="access-secondary" disabled={busy||remaining>0} onClick={()=>void sendCode(email)}>{remaining>0?`Resend available in ${remaining}s`:'Resend code'}</button><button className="access-secondary" disabled={busy} onClick={()=>{setSent(false);setError('');}}>Use a different email</button></>:<Link className="access-secondary" to={signup?'/login':'/signup'}>{signup?'Already have an account? Sign in':'New to Relay? Create an account'}</Link>}<div className="access-note"><strong>Private by company.</strong><span>Your company information stays in your private workspace. The example workspace remains separate.</span></div><Link className="access-secondary" to="/app">Explore the local demo <ArrowUpRight size={14}/></Link></section></main><PublicFooter/></div>;
}
export function CloudWorkspace() {
 const navigate=useNavigate(); const notify=useFeedback(); const [user,setUser]=useState<User|null>(null); const [org,setOrg]=useState<Row<'organizations'>|null>(null); const [suppliers,setSuppliers]=useState<Row<'suppliers'>[]>([]); const [documents,setDocuments]=useState<Row<'documents'>[]>([]); const [requests,setRequests]=useState<Row<'data_requests'>[]>([]); const [connections,setConnections]=useState<Row<'supplier_relationships'>[]>([]); const [tab,setTab]=useState('Suppliers'); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [dialog,setDialog]=useState<'supplier'|'document'|'request'|null>(null);
 async function load() {setLoading(true);setError('');try {const client=requireSupabase();const {data:auth,error:authError}=await client.auth.getUser();if(authError||!auth.user){navigate('/login',{replace:true});return;}setUser(auth.user);let {data:organizations,error:orgError}=await client.from('organizations').select('*').order('created_at').limit(1);if(orgError)throw orgError;
 if(!organizations?.length){const {error}=await client.rpc('create_workspace',{company_name:String(auth.user.user_metadata.company_name||'My company'),full_name:String(auth.user.user_metadata.full_name||'')});if(error)throw error;const result=await client.from('organizations').select('*').order('created_at').limit(1);if(result.error)throw result.error;organizations=result.data;}
 const company=organizations?.[0];if(!company)throw new Error('Company workspace could not be loaded.');setOrg(company);
 const results=await Promise.all([client.from('suppliers').select('*').eq('organization_id',company.id).order('legal_name'),client.from('documents').select('*').eq('organization_id',company.id).order('uploaded_at',{ascending:false}),client.from('data_requests').select('*').eq('organization_id',company.id).order('requested_at',{ascending:false}),client.from('supplier_relationships').select('*').eq('organization_id',company.id)]);
 for(const result of results)if(result.error)throw result.error;setSuppliers(results[0].data||[]);setDocuments(results[1].data||[]);setRequests(results[2].data||[]);setConnections(results[3].data||[]);
 }catch(e){setError(message(e));}finally{setLoading(false);} }
 useEffect(()=>{void load();const {data:{subscription}}=requireSupabase().auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')navigate('/login',{replace:true});});return()=>subscription.unsubscribe();},[]);
 async function submit(event:FormEvent<HTMLFormElement>) {event.preventDefault();if(!org||!user)return;setBusy(true);setError('');const f=new FormData(event.currentTarget);const client=requireSupabase();try {
 if(dialog==='supplier'){const {error}=await client.rpc('add_supplier_connection',{org_id:org.id,company_name:String(f.get('name')).trim(),country_name:String(f.get('country')).trim(),country_iso:String(f.get('code')).toUpperCase(),supplier_category:String(f.get('category')||''),email:String(f.get('email')||'')});if(error)throw error;notify('Supplier connected.','Saved in your company workspace.');}
 if(dialog==='request'){const {error}=await client.rpc('prepare_information_request',{connection_id:String(f.get('connection')),request_title:String(f.get('title')).trim(),due_date:String(f.get('due'))});if(error)throw error;notify('Request prepared.','Saved in Relay. Email delivery is not connected yet.');}
 if(dialog==='document'){const file=f.get('file');if(!(file instanceof File)||!file.size)throw new Error('Choose a document.');if(file.size>10*1024*1024||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw new Error('Choose a PDF, PNG or JPEG up to 10 MB.');const supplier=String(f.get('supplier'));const id=crypto.randomUUID();const filename=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${org.id}/${supplier}/${id}/${filename}`;
 const uploaded=await client.storage.from('relay-documents').upload(path,file,{upsert:false,contentType:file.type});if(uploaded.error)throw uploaded.error;
 const saved=await client.from('documents').insert({id,organization_id:org.id,supplier_id:supplier,name:file.name,kind:f.get('kind') as 'certificate'|'declaration'|'company',mime_type:file.type,storage_path:path,uploaded_by:user.id});if(saved.error)throw new Error('The file uploaded but its record could not be saved. Please contact support before uploading it again.');notify('Document saved.','Private storage. Awaiting review.');}
 setDialog(null);await load();}catch(e){setError(message(e));}finally{setBusy(false);} }
 async function download(document:Row<'documents'>){try{const {data,error}=await requireSupabase().storage.from('relay-documents').download(document.storage_path);if(error)throw error;const url=URL.createObjectURL(data);const a=window.document.createElement('a');a.href=url;a.download=document.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notify('Download unavailable.',message(e));}}
 async function signOut(){const {error}=await requireSupabase().auth.signOut();if(error)setError(error.message);else navigate('/login');}
 return <div className="public-site"><header className="public-header"><Link className="wordmark" to="/">relay<span>↗</span></Link><span className="cloud-company">{org?.legal_name||'Your workspace'}</span><Badge>CONNECTED</Badge><Button variant="ghost" onClick={()=>void signOut()}><LogOut size={15}/>Sign out</Button></header><main id="main" tabIndex={-1} className="public-main cloud-main"><div className="page-header"><div><p className="eyebrow">YOUR COMPANY WORKSPACE</p><h1>Your network.<br/>Connected.</h1><p className="page-description">Company information and private documents, together.</p></div><Button variant="ghost" aria-label="Refresh workspace" disabled={loading} onClick={()=>void load()}><RefreshCw size={17}/></Button></div>{error&&<p role="alert" className="form-error cloud-error">{error}</p>}{loading?<p role="status" className="quiet-note">Loading your company workspace…</p>:<><div className="cloud-metrics"><div><strong>{suppliers.length}</strong><span>Suppliers</span></div><div><strong>{documents.length}</strong><span>Documents</span></div><div><strong>{requests.length}</strong><span>Prepared requests</span></div></div><div className="cloud-toolbar"><div className="filter-tabs">{['Suppliers','Documents','Requests'].map(t=><button key={t} className={t===tab?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div><Button disabled={busy||(tab!=='Suppliers'&&!suppliers.length)} onClick={()=>{setError('');setDialog(tab==='Suppliers'?'supplier':tab==='Documents'?'document':'request');}}><Plus size={15}/>{tab==='Suppliers'?'Add supplier':tab==='Documents'?'Upload document':'Prepare request'}</Button></div>
 {tab==='Suppliers'&&(suppliers.length?suppliers.map(s=><div className="list-row" key={s.id}><span className="company-monogram">{s.legal_name[0]}</span><div className="row-copy"><strong>{s.legal_name}</strong><small>{s.country} · {s.category||'Supplier'}</small></div><Badge>REVIEW REQUIRED</Badge></div>):<EmptyState title="Your first connection." description="Add a supplier to start building your company network."/>)}
 {tab==='Documents'&&(documents.length?documents.map(d=><div className="list-row" key={d.id}><div className="row-copy"><strong>{d.name}</strong><small>{suppliers.find(s=>s.id===d.supplier_id)?.legal_name}</small></div><Badge>{d.verification_status==='verified'?'REVIEWED':'AWAITING REVIEW'}</Badge><Button variant="ghost" aria-label={`Download ${d.name}`} onClick={()=>void download(d)}><Download size={17}/></Button></div>):<EmptyState title="Give evidence a place." description="Upload a document against a supplier. Your files stay private to your company."/>)}
 {tab==='Requests'&&(requests.length?requests.map(r=><div className="list-row" key={r.id}><div className="row-copy"><strong>{r.title}</strong><small>Due {r.due_at}</small></div><Badge>PREPARED</Badge></div>):<EmptyState title="A clear next step." description="Prepare a request for a supplier's missing company and compliance information."/>)}<p className="quiet-note">Connected to your Relay company. Requests are saved as drafts; supplier invitations and email delivery still need configuration.</p></>}
 </main><PublicFooter/><Dialog open={dialog!==null} onClose={()=>{if(!busy)setDialog(null);}} title={dialog==='supplier'?'The next connection.':dialog==='document'?'Give information a place.':'A clear next step.'}><form className="workspace-form" onSubmit={submit}>{dialog==='supplier'?<><label>Company name<Input required name="name" maxLength={160}/></label><div className="form-grid"><label>Country<Input required name="country" maxLength={80}/></label><label>Country code<Input required name="code" pattern="[A-Za-z]{2}" maxLength={2} placeholder="AT"/></label></div><label>Category<Input name="category" maxLength={100}/></label><label>Contact email<Input type="email" name="email" maxLength={254}/></label></>:dialog==='document'?<><label>Supplier<select required name="supplier">{suppliers.map(s=><option key={s.id} value={s.id}>{s.legal_name}</option>)}</select></label><label>Document type<select name="kind"><option value="certificate">Certificate</option><option value="declaration">Declaration</option><option value="company">Company information</option></select></label><label className="file-drop">PDF, PNG or JPEG · Up to 10 MB<input required name="file" type="file" accept="application/pdf,image/png,image/jpeg"/></label></>:<><label>Supplier<select required name="connection">{connections.map(c=><option key={c.id} value={c.id}>{suppliers.find(s=>s.id===c.supplier_id)?.legal_name}</option>)}</select></label><label>Request title<Input required name="title" maxLength={160}/></label><label>Due date<Input required name="due" type="date" min={new Date().toISOString().slice(0,10)}/></label></>}{error&&<p role="alert" className="form-error">{error}</p>}<Button type="submit" disabled={busy}>{busy?'Saving…':'Save to workspace'}<ArrowUpRight size={16}/></Button></form><p className="dialog-footnote">Data is stored in your Relay company. No supplier invitation is sent.</p></Dialog></div>;
}
