/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiAdminActionRouteImport } from './routes/api/admin/action'
import { Route as ApiAuthEmailHookRouteImport } from './routes/api/auth/email-hook'
import { Route as ApiWorkspaceInviteRouteImport } from './routes/api/workspace/invite'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActionRoute = ApiAdminActionRouteImport.update({
  id: '/api/admin/action',
  path: '/api/admin/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEmailHookRoute = ApiAuthEmailHookRouteImport.update({
  id: '/api/auth/email-hook',
  path: '/api/auth/email-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceInviteRoute = ApiWorkspaceInviteRouteImport.update({
  id: '/api/workspace/invite',
  path: '/api/workspace/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/admin/action': typeof ApiAdminActionRoute
  '/api/auth/email-hook': typeof ApiAuthEmailHookRoute
  '/api/workspace/invite': typeof ApiWorkspaceInviteRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/admin/action': typeof ApiAdminActionRoute
  '/api/auth/email-hook': typeof ApiAuthEmailHookRoute
  '/api/workspace/invite': typeof ApiWorkspaceInviteRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/admin/action': typeof ApiAdminActionRoute
  '/api/auth/email-hook': typeof ApiAuthEmailHookRoute
  '/api/workspace/invite': typeof ApiWorkspaceInviteRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/admin/action'
    | '/api/auth/email-hook'
    | '/api/workspace/invite'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/admin/action'
    | '/api/auth/email-hook'
    | '/api/workspace/invite'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/admin/action'
    | '/api/auth/email-hook'
    | '/api/workspace/invite'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiAdminActionRoute: typeof ApiAdminActionRoute
  ApiAuthEmailHookRoute: typeof ApiAuthEmailHookRoute
  ApiWorkspaceInviteRoute: typeof ApiWorkspaceInviteRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/action': {
      id: '/api/admin/action'
      path: '/api/admin/action'
      fullPath: '/api/admin/action'
      preLoaderRoute: typeof ApiAdminActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/email-hook': {
      id: '/api/auth/email-hook'
      path: '/api/auth/email-hook'
      fullPath: '/api/auth/email-hook'
      preLoaderRoute: typeof ApiAuthEmailHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace/invite': {
      id: '/api/workspace/invite'
      path: '/api/workspace/invite'
      fullPath: '/api/workspace/invite'
      preLoaderRoute: typeof ApiWorkspaceInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiAdminActionRoute: ApiAdminActionRoute,
  ApiAuthEmailHookRoute: ApiAuthEmailHookRoute,
  ApiWorkspaceInviteRoute: ApiWorkspaceInviteRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
